name: Auto Update And Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
     - name: Git Checkout
       uses: actions/checkout@v2
       with: 
          ref: main
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v1
       with:
         node-version: ${{ matrix.node-version }}
     - name: Set Dependencies Cache
       uses: actions/cache@v2
       id: yarn-cache
       with:
         path: '**/node_modules/**/*'
         key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
         restore-keys: |
           ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
     - name: Install Dependencies
       uses: borales/actions-yarn@v2.0.0
       if: steps.yarn-cache.outputs.cache-hit != 'true'
       with:
         cmd: install 

     - name: changeFile
       run: npm run changeFile
    
     - name: Git Commit And Push
       uses: stefanzweifel/git-auto-commit-action@v4
       with:
         commit_message: 'chore: Updated last-commit-hash'
         branch: main
         skip_dirty_check: true

  deploy:
    runs-on: ubuntu-latest  
    needs: update
    strategy:
      matrix:
        node-version: [12.x]
    steps:
     - name: Git Checkout
       uses: actions/checkout@v2
       with: 
          ref: main
          persist-credentials: false

     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v1
       with:
         node-version: ${{ matrix.node-version }}

     - name: Set Dependencies Cache
       uses: actions/cache@v2
       id: yarn-cache
       with:
         path: '**/node_modules/**/*'
         key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
         restore-keys: |
           ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

     - name: Install Dependencies
       uses: borales/actions-yarn@v2.0.0
       if: steps.yarn-cache.outputs.cache-hit != 'true'
       with:
         cmd: install 

     - name: Build Docs
       uses: borales/actions-yarn@v2.0.0
       with:
         cmd: build 

     - name: Deploy Docs
       uses: JamesIves/github-pages-deploy-action@releases/v3
      #  uses: ./.github/actions/deploy
       with:
         ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
         BRANCH: releases
         FOLDER: dist
         PRESERVE: true